const {test}=require('node:test');const assert=require('node:assert/strict');const {spawn}=require('node:child_process');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {DatabaseSync}=require('node:sqlite');
test('authentification, origine et sauvegarde SQLite',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'geststock-auth-'));
 const password='test-only-password-12345';
 const child=spawn(process.execPath,['server.js'],{cwd:path.join(__dirname,'..'),env:{...process.env,ALLOW_LOCAL_NO_AUTH:'0',HOST:'127.0.0.1',PORT:'3101',ADMIN_USER:'admin',ADMIN_PASSWORD:password,DB_PATH:path.join(dir,'stock.db')}});
 try{
 await new Promise((resolve,reject)=>{child.stdout.once('data',resolve);child.once('error',reject);child.once('exit',c=>reject(Error('Startup '+c)));});
 const url='http://127.0.0.1:3101';
 const unauthenticated=await fetch(url,{redirect:'manual'});assert.equal(unauthenticated.status,303);assert.equal(unauthenticated.headers.get('location'),'/login');assert.equal(unauthenticated.headers.get('www-authenticate'),null);
 assert.match(await(await fetch(url+'/login')).text(),/login-form/);assert.equal((await fetch(url+'/login.js')).status,200);
 assert.equal((await fetch(url+'/api/state')).status,401);assert.equal((await fetch(url+'/api/attachments/1')).status,401);
 const login=credentials=>fetch(url+'/api/login',{method:'POST',headers:{'Content-Type':'application/json',Origin:url},body:JSON.stringify(credentials)});
 assert.equal((await login({username:'admin',password:'wrong'})).status,401);
 const response=await login({username:'admin',password});assert.equal(response.status,200);
 const cookie=response.headers.get('set-cookie');assert.match(cookie,/HttpOnly/);assert.match(cookie,/SameSite=Strict/);
 const auth={Cookie:cookie.split(';')[0]};
 assert.equal((await fetch(url,{headers:auth})).status,200);assert.equal((await fetch(url+'/api/state',{headers:auth})).status,200);
 assert.equal((await fetch(url+'/api/settings',{method:'POST',headers:{...auth,Origin:'https://other.example'},body:'{}'})).status,403);
 assert.equal((await fetch(url+'/api/settings',{method:'POST',headers:{...auth,Origin:url},body:'{}'})).status,200);
 const changeUser=(headers,body)=>fetch(url+'/api/users',{method:'POST',headers:{...headers,Origin:url,'Content-Type':'application/json'},body:JSON.stringify(body)});
 const employee={username:'employee',name:'Employé',role:'user',active:true,password:'employee-test-pass-12345'};
 assert.equal((await changeUser(auth,employee)).status,200);
 assert.equal((await changeUser(auth,{...employee,username:'EMPLOYEE'})).status,400);
 let state=await(await fetch(url+'/api/state',{headers:auth})).json();
 assert.equal(state.currentUser.role,'admin');assert.equal(state.users.length,2);assert.ok(!JSON.stringify(state).includes('password_hash'));
 const id=state.users.find(u=>u.username==='employee').id;
 const loginEmployee=await login({username:'employee',password:employee.password});assert.equal(loginEmployee.status,200);
 const staffAuth={Cookie:loginEmployee.headers.get('set-cookie').split(';')[0]};
 assert.equal((await changeUser(staffAuth,{...employee,username:'another'})).status,403);
 assert.equal((await fetch(url+'/api/settings',{method:'POST',headers:{...staffAuth,Origin:url},body:'{}'})).status,403);
 assert.equal((await fetch(url+'/api/expensePayments',{method:'POST',headers:{...staffAuth,Origin:url},body:JSON.stringify({id:123,action:'validate'})})).status,403);
 assert.equal((await fetch(url+'/api/banks',{method:'POST',headers:{...staffAuth,Origin:url},body:JSON.stringify({name:'Banque',active:true})})).status,403);
 assert.equal((await fetch(url+'/api/products',{method:'POST',headers:{...staffAuth,Origin:url},body:JSON.stringify({name:'Staff article',price:10,stock:2,min:1})})).status,200);
 state=await(await fetch(url+'/api/state',{headers:staffAuth})).json();assert.deepEqual(state.users,[]);
 const admin= (await(await fetch(url+'/api/state',{headers:auth})).json()).users.find(u=>u.role==='admin');
 assert.equal((await changeUser(auth,{...admin,role:'user',password:''})).status,400);
 assert.equal((await changeUser(auth,{...employee,id,active:false,password:''})).status,200);
 assert.equal((await fetch(url+'/api/state',{headers:staffAuth})).status,401);
 assert.equal((await login({username:'employee',password:employee.password})).status,401);
 assert.equal((await changeUser(auth,{...employee,id,password:'replacement-password-12345'})).status,200);
 assert.equal((await login({username:'employee',password:employee.password})).status,401);
 assert.equal((await login({username:'employee',password:'replacement-password-12345'})).status,200);
 const persisted=new DatabaseSync(path.join(dir,'stock.db'));const saved=persisted.prepare("SELECT password_hash FROM users WHERE username='employee'").get();assert.ok(saved.password_hash.includes(':'));assert.ok(!saved.password_hash.includes('replacement'));persisted.close();
 assert.equal((await fetch(url+'/api/logout',{method:'POST',headers:{...auth,Origin:url},body:'{}'})).status,200);
 assert.equal((await fetch(url+'/api/state',{headers:auth})).status,401);
 await new Promise(r=>setTimeout(r,100));const file=fs.readdirSync(path.join(dir,'backups')).find(f=>f.endsWith('.db'));assert.ok(file);
 const db=new DatabaseSync(path.join(dir,'backups',file));assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');assert.ok(db.prepare("SELECT name FROM sqlite_master WHERE name='records'").get());db.close();
 }finally{await new Promise(r=>{child.once('exit',r);child.kill();});fs.rmSync(dir,{recursive:true,force:true});}
});
