const {test}=require('node:test');const assert=require('node:assert/strict');const {spawn}=require('node:child_process');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
test('devis, facture, stock insuffisant, réception et persistance',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'geststock-'));let child;
 const start=()=>new Promise((resolve,reject)=>{child=spawn(process.execPath,['server.js'],{cwd:path.join(__dirname,'..'),env:{...process.env,PORT:'3099',HOST:'127.0.0.1',ALLOW_LOCAL_NO_AUTH:'1',DB_PATH:path.join(dir,'test.db')}});child.stdout.once('data',resolve);child.once('error',reject);child.once('exit',code=>{if(code)reject(Error('Serveur arrêté '+code));});});
 const request=async(k,body)=>{const r=await fetch('http://127.0.0.1:3099/api/'+k,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};};
 try{await start();assert.equal((await fetch('http://127.0.0.1:3099/')).status,200);const p=(await request('products',{name:'Article',barcode:'0012345678905',sku:'VEND-1',purchasePrice:60,price:100,stock:5,min:2})).data.id;const c=(await request('clients',{name:'Client test'})).data.id;
 const doc={type:'Devis',clientId:c,tax:20,lines:[{productId:p,qty:2}]};assert.equal((await request('documents',doc)).status,200);assert.equal((await request('state')).data.products[0].stock,5);
 assert.equal((await request('documents',{...doc,type:'Facture'})).status,200);let s=(await request('state')).data;assert.equal(s.products[0].stock,3);assert.equal(s.documents[0].total,240);
 assert.equal((await request('documents',{...doc,type:'Facture',lines:[{productId:p,qty:2},{productId:p,qty:2}]})).status,400);s=(await request('state')).data;assert.equal(s.products[0].stock,3);assert.equal(s.documents.length,2);
 assert.equal((await request('movements',{productId:p,qty:4,reference:'REC-1'})).status,200);assert.equal((await request('state')).data.products[0].stock,7);
 assert.equal((await request('cheques',{beneficiary:'Fournisseur',amount:120,words:'Texte incorrect',city:'Autre ville'})).status,200);
 assert.equal((await request('products',{name:'Invalid',price:100,stock:0,min:0,purchasePrice:-1})).status,400);
 const chequePrint=(await request('state')).data.cheques[0];assert.equal(chequePrint.words,'Cent vingt dirhams');assert.equal(chequePrint.city,'Rabat');
 const productUpdate={id:p,name:'Article modifié',sku:'NEW',price:150,stock:7,min:3,expectedStock:7};
 assert.equal((await request('products',productUpdate)).status,200);
 assert.equal((await request('products',{...productUpdate,stock:9})).status,400);
 assert.equal((await request('products',{...productUpdate,id:99999})).status,400);
 s=(await request('state')).data;assert.equal(s.products.length,1);assert.equal(s.products[0].price,150);assert.equal(s.products[0].barcode,'0012345678905');assert.equal(s.products[0].purchasePrice,60);assert.equal(s.products[0].stock,7);assert.equal(s.documents[0].lines[0].price,100);assert.equal(s.documents[0].lines[0].name,'Article');
 assert.equal((await request('products',{...productUpdate,expectedStock:8,price:-1})).status,400);
 const updated={id:c,name:'Client modifié',phone:'0600000000',email:'client@example.com',address:'Rabat',ice:'123'};
 assert.equal((await request('clients',updated)).status,200);
 s=(await request('state')).data;assert.equal(s.clients.length,1);assert.equal(s.clients[0].phone,updated.phone);assert.equal(s.clients[0].id,c);assert.equal(s.documents[0].clientName,'Client test');
 assert.equal((await request('clients',{...updated,name:''})).status,400);
 assert.equal((await request('clients',{...updated,id:99999})).status,400);
 const supplier=(await request('suppliers',{name:'Fournisseur'})).data.id;
 assert.equal((await request('suppliers',{id:supplier,name:'Fournisseur modifié',address:'Casa'})).status,200);
 assert.equal((await request('suppliers',{...updated})).status,400);
 const expenseBody={label:'Loyer',category:'Local',amount:1000,date:'2026-10-08',supplierId:supplier,reference:'LOY-1'};
 const expense=(await request('expenses',expenseBody)).data.id;assert.ok(expense);
 const pdf=Buffer.from('%PDF-1.4\nJustificatif test');
 const payment={expenseId:expense,amount:300,date:'2026-10-08',method:'App banque',reference:'VIR-1',supplierId:supplier,attachment:{name:'preuve.pdf',mime:'application/pdf',base64:pdf.toString('base64')}};
 assert.equal((await request('expensePayments',{...payment,attachment:{name:'bad.pdf',mime:'application/pdf',base64:Buffer.from('not a pdf').toString('base64')}})).status,400);
 assert.equal((await request('expensePayments',{...payment,supplierId:99999})).status,400);
 assert.equal((await request('expensePayments',payment)).status,200);
 assert.equal((await request('expensePayments',{...payment,amount:701})).status,400);
 assert.equal((await request('expensePayments',{...payment,amount:700})).status,200);
 assert.equal((await request('expensePayments',{...payment,amount:0.01})).status,400);
 assert.equal((await request('expenses',{...expenseBody,amount:-1})).status,400);
 assert.equal((await request('expenses',{...expenseBody,date:'2026-02-30'})).status,400);
 assert.equal((await request('expenses',{...expenseBody,amount:1.234})).status,400);
 assert.equal((await request('expensePayments',{...payment,expenseId:99999})).status,400);
 s=(await request('state')).data;assert.equal(s.expenses.length,5);assert.equal(s.expensePayments.length,2);assert.equal(s.expensePayments.reduce((sum,p)=>sum+p.amountCents,0),100000);
 const paidRecord=(await request('state')).data.expensePayments.find(x=>x.amount===300);assert.equal(paidRecord.method,'App banque');assert.equal(paidRecord.supplierId,supplier);assert.equal(paidRecord.supplierName,'Fournisseur modifié');assert.ok(paidRecord.attachment.id);
 const downloaded=await fetch('http://127.0.0.1:3099/api/attachments/'+paidRecord.attachment.id);assert.equal(downloaded.status,200);assert.match(downloaded.headers.get('content-disposition'),/attachment/);assert.deepEqual(Buffer.from(await downloaded.arrayBuffer()),pdf);
 const bank=(await request('state')).data.banks.find(x=>x.name==='CDM');assert.ok(bank);assert.equal((await request('state')).data.banks.length,3);
 const chequeExpense=(await request('expenses',{...expenseBody,label:'Charge par chèque',amount:200})).data.id;
 const chequePayment={expenseId:chequeExpense,amount:200,date:'2026-10-08',method:'Chèque',bankId:bank.id,chequeNumber:'CH-123',chequeDueDate:'2026-11-01'};
 assert.equal((await request('expensePayments',{...chequePayment,bankId:0})).status,400);
 assert.equal((await request('expensePayments',{...chequePayment,chequeDueDate:'2026-02-30'})).status,400);
 assert.equal((await request('expensePayments',{...chequePayment,chequeNumber:''})).status,400);
 assert.equal((await request('banks',{...bank,active:false})).status,200);
 assert.equal((await request('expensePayments',chequePayment)).status,400);
 assert.equal((await request('banks',{...bank,active:true,account:'Compte principal'})).status,200);
 assert.equal((await request('expensePayments',chequePayment)).status,200);
 assert.equal((await request('banks',{...bank,name:'CDM modifiée',active:true})).status,200);
 const recorded=(await request('state')).data.expensePayments.find(x=>x.expenseId===chequeExpense);assert.equal(recorded.bankName,'CDM');assert.equal(recorded.bankAccount,'Compte principal');assert.equal(recorded.chequeNumber,'CH-123');assert.equal(recorded.chequeDueDate,'2026-11-01');
 assert.equal(recorded.status,'pending');
 assert.equal((await request('expensePayments',{...chequePayment,amount:1})).status,400);
 const attach={id:recorded.id,expectedUpdatedAt:recorded.updatedAt,action:'attachment',attachment:{name:'signed.pdf',mime:'application/pdf',base64:pdf.toString('base64')}};
 assert.equal((await request('expensePayments',attach)).status,200);
 let cheque=(await request('state')).data.expensePayments.find(x=>x.id===recorded.id);assert.equal(cheque.status,'pending');assert.equal(cheque.attachment.name,'signed.pdf');assert.equal(cheque.history.length,1);
 assert.equal((await request('expensePayments',{id:cheque.id,expectedUpdatedAt:recorded.updatedAt,action:'validate',clearedDate:'2026-10-08'})).status,400);
 const edited={...cheque,expectedUpdatedAt:cheque.updatedAt,bankId:bank.id,notes:'Corrigé par admin'};delete edited.attachment;
 assert.equal((await request('expensePayments',edited)).status,200);
 cheque=(await request('state')).data.expensePayments.find(x=>x.id===recorded.id);assert.equal(cheque.notes,'Corrigé par admin');assert.equal(cheque.status,'pending');assert.equal(cheque.attachment.name,'signed.pdf');
 assert.equal((await request('expensePayments',{id:cheque.id,expectedUpdatedAt:cheque.updatedAt,action:'validate',clearedDate:'2026-02-30'})).status,400);
 assert.equal((await request('expensePayments',{id:cheque.id,expectedUpdatedAt:cheque.updatedAt,action:'validate',clearedDate:'2026-10-08'})).status,200);
 cheque=(await request('state')).data.expensePayments.find(x=>x.id===recorded.id);assert.equal(cheque.status,'validated');assert.equal(cheque.clearedDate,'2026-10-08');assert.ok(cheque.validatedBy);
 assert.equal((await request('expensePayments',{id:cheque.id,expectedUpdatedAt:cheque.updatedAt,action:'validate',clearedDate:'2026-10-08'})).status,400);
 const changedCheque={...cheque,expectedUpdatedAt:cheque.updatedAt,chequeNumber:'CH-456'};delete changedCheque.attachment;
 assert.equal((await request('expensePayments',changedCheque)).status,200);
 assert.equal((await request('state')).data.expensePayments.find(x=>x.id===recorded.id).status,'pending');
 const deactivate={id:chequeExpense,action:'setActive',active:false,expectedActive:true,reason:'Saisie en double'};
 assert.equal((await request('expenses',{...deactivate,reason:''})).status,400);
 assert.equal((await request('expenses',deactivate)).status,200);
 s=(await request('state')).data;assert.equal(s.expenses.find(x=>x.id===chequeExpense).active,false);assert.equal(s.expensePayments.filter(x=>x.expenseId===chequeExpense).length,1);assert.equal(s.expenseLifecycleHistory.length,1);assert.equal(s.expenseLifecycleHistory[0].reason,'Saisie en double');assert.ok(s.expenseLifecycleHistory[0].actor);
 assert.equal((await request('expenses',deactivate)).status,400);
 assert.equal((await request('expensePayments',{...chequePayment,amount:1})).status,400);
 const archivedCheque=s.expensePayments.find(x=>x.id===recorded.id);
 assert.equal((await request('expensePayments',{id:archivedCheque.id,expectedUpdatedAt:archivedCheque.updatedAt,action:'validate',clearedDate:'2026-10-08'})).status,400);
 assert.equal((await request('expenses',{...deactivate,active:true,expectedActive:false,reason:'Correction vérifiée'})).status,200);
 assert.equal((await request('state')).data.expenseLifecycleHistory.length,2);
 assert.equal((await request('state')).data.expenses.find(x=>x.id===chequeExpense).active,true);
 const periodic=(await request('state')).data.recurringCharges.find(x=>x.label==='WIFI');
 assert.equal((await request('recurringCharges',{...periodic,amount:199,active:false,supplierId:supplier})).status,200);
 let changed=(await request('state')).data.recurringCharges.find(x=>x.id===periodic.id);assert.equal(changed.amount,199);assert.equal(changed.active,false);assert.equal(changed.supplierId,supplier);
 assert.equal((await request('recurringCharges',{...changed,amount:0})).status,400);

 const pendingId=(await request('movements',{productId:p,supplierId:supplier,qty:10,unitPrice:25,status:'pending',reference:'ACH-PENDING'})).data.id;
 let current=(await request('state')).data;assert.equal(current.products[0].stock,7);let pending=current.movements.find(m=>m.id===pendingId);
 assert.equal((await request('movements',{id:pendingId,action:'receive',expectedRecord:JSON.stringify(pending)})).status,200);current=(await request('state')).data;assert.equal(current.products[0].stock,17);
 assert.equal((await request('movements',{id:pendingId,action:'receive',expectedRecord:JSON.stringify(pending)})).status,400);
 assert.equal((await request('inventories',{productId:p,counted:15,expectedStock:7,reason:'Comptage'})).status,400);
 const inventoryId=(await request('inventories',{productId:p,counted:15,expectedStock:17,reason:'Comptage'})).data.id;current=(await request('state')).data;assert.equal(current.products[0].stock,15);assert.equal(current.products[0].adjustment,-2);
 const inventory=current.inventories.find(i=>i.id===inventoryId);assert.equal((await request('adminRecords',{kind:'inventories',id:inventoryId,action:'setActive',active:false,expectedRecord:JSON.stringify(inventory),reason:'Correction'})).status,200);current=(await request('state')).data;assert.equal(current.products[0].stock,17);
 pending=current.movements.find(m=>m.id===pendingId);assert.equal((await request('adminRecords',{kind:'movements',id:pendingId,action:'setActive',active:false,expectedRecord:JSON.stringify(pending),reason:'Achat annulé'})).status,200);assert.equal((await request('state')).data.products[0].stock,7);
 await new Promise(resolve=>{child.once('exit',resolve);child.kill();});await start();assert.equal((await request('state')).data.products[0].stock,7);assert.equal((await request('state')).data.clients[0].name,'Client modifié');assert.equal((await request('state')).data.expensePayments.length,3);assert.equal((await request('state')).data.recurringCharges.find(x=>x.label==='WIFI').active,false);assert.equal((await fetch('http://127.0.0.1:3099/api/attachments/'+paidRecord.attachment.id)).status,200);assert.equal((await request('state')).data.expenseLifecycleHistory.length,2);

 const p2=(await request('products',{name:'Deuxième',price:80,stock:0,min:1})).data.id;
 const bon={supplierId:supplier,status:'pending',reference:'BON-MULTI',lines:[{productId:p,qty:3,unitPrice:20,discount:10},{productId:p2,qty:2,unitPrice:40,discount:0}]};
 const countBefore=(await request('state')).data.movements.length;
 assert.equal((await request('movements',{...bon,lines:[bon.lines[0],{...bon.lines[1],productId:99999}]})).status,400);assert.equal((await request('state')).data.movements.length,countBefore);
 const multiId=(await request('movements',bon)).data.id;let multiState=(await request('state')).data;let multi=multiState.movements.find(m=>m.id===multiId);assert.equal(multi.lines.length,2);assert.equal(multi.total,134);assert.equal(multiState.products.find(x=>x.id===p).stock,7);assert.equal(multiState.products.find(x=>x.id===p2).stock,0);
 assert.equal((await request('movements',{id:multiId,action:'receive',expectedRecord:JSON.stringify(multi)})).status,200);multiState=(await request('state')).data;assert.equal(multiState.products.find(x=>x.id===p).stock,10);assert.equal(multiState.products.find(x=>x.id===p2).stock,2);
 multi=multiState.movements.find(m=>m.id===multiId);assert.equal((await request('adminRecords',{kind:'movements',id:multiId,action:'modify',expectedRecord:JSON.stringify(multi),reason:'Quantité corrigée',data:{supplierId:supplier,reference:bon.reference,lines:[{...bon.lines[0],qty:4},bon.lines[1]]}})).status,200);multiState=(await request('state')).data;assert.equal(multiState.products.find(x=>x.id===p).stock,11);
 multi=multiState.movements.find(m=>m.id===multiId);assert.equal((await request('adminRecords',{kind:'movements',id:multiId,action:'setActive',active:false,expectedRecord:JSON.stringify(multi),reason:'Annulation bon'})).status,200);multiState=(await request('state')).data;assert.equal(multiState.products.find(x=>x.id===p).stock,7);assert.equal(multiState.products.find(x=>x.id===p2).stock,0);

 const payableBill=(await request('movements',{supplierId:supplier,status:'received',lines:[{productId:p,qty:1,unitPrice:20}]})).data.id;
 const groupedPayment={side:'supplier',partyId:supplier,billIds:[payableBill],amount:20,date:'2026-10-08',method:'Espèces',expectedBalances:{[payableBill]:2000}};
 assert.equal((await request('settlements',groupedPayment)).status,200);assert.equal((await request('settlements',groupedPayment)).status,400);
 assert.equal((await request('accountOpenings',{bankId:0,amount:1000,date:'2026-10-01',reason:'Départ caisse'})).status,200);assert.equal((await request('state')).data.accountOpenings[0].amountCents,100000);
 assert.equal((await fetch('http://127.0.0.1:3099/settlement-math.js')).status,200);assert.equal((await fetch('http://127.0.0.1:3099/settlements.js')).status,200);
 }finally{if(child&&!child.killed)await new Promise(resolve=>{child.once('exit',resolve);child.kill();});fs.rmSync(dir,{recursive:true,force:true});}
});
